define({
  root: ({
    _widgetLabel: "Dibujar",
    selectDrawMode: "Seleccionar modo de dibujo",
    clear: "Borrar",
    point: "Punto",
    line: "Línea",
    polyline: "Polilínea",
    freehandPolyline: "Polilínea a mano alzada",
    triangle: "Triángulo",
    extent: "Contorno",
    circle: "Círculo",
    ellipse: "Elipse",
    polygon: "Polígono",
    freehandPolygon: "Polígono a mano alzada",
    text: "Texto",
    style: "Estilo",
    alpha: "Transparencia",
    width: "Ancho",
    size: "Tamaño",
    color: "Color",
    markerColor: "Color de marca",
    outlineColor: "Color del contorno",
    lineColor: "Color de línea",
    fillColor: "Color de relleno",
    showMeasurements: "Mostrar medidas",
    showLocationMeasurement: "Mostrar medición de ubicación",
    showAreaMeasurement: "Mostrar medición de área",
    showDistanceMeasurement: "Mostrar medición de distancia",
    showDistanceMeasurementForLine: "Mostrar medición de longitud",
    showDistanceMeasurementForPolygon: "Mostrar medición de perímetro",
    locationToggleOn: "Pulse el botón de alternancia para mostrar la medición de ubicación",
    locationToggleOff: "Pulse el botón de alternancia para ocultar la medición de ubicación",
    areaToggleOn: "Pulse el botón de alternancia para mostrar la medición de área",
    areaToggleOff: "Pulse el botón de alternancia para ocultar la medición de área",
    distanceForLineToggleOn: "Pulse el botón de alternancia para mostrar la medición de longitud",
    distanceForLineToggleOff: "Pulse el botón de alternancia para ocultar la medición de longitud",
    distanceForPolygonToggleOn: "Pulse el botón de alternancia para mostrar la medición de perímetro",
    distanceForPolygonToggleOff: "Pulse el botón de alternancia para ocultar la medición de perímetro",
    areaUnits: "Unidades de área",
    distanceUnits: "Unidades de distancia",
    kilometers: "Kilómetros",
    miles: "Millas",
    meters: "Metros",
    feet: "Pies",
    yards: "Yardas",
    nauticalmiles: "Millas náuticas",
    squareKilometers: "Kilómetros cuadrados",
    squareMiles: "Millas cuadradas",
    acres: "Acres",
    hectares: "Hectáreas",
    squareMeters: "Metros cuadrados",
    squareFeet: "Pies cuadrados",
    squareYards: "Yardas cuadradas",
    undo: "Deshacer",
    redo: "Rehacer",
    results: "Resultados",
    points: "Puntos",
    lines: "Líneas",
    areas: "Áreas",
    locationLabel: "Ubicación: ${value}",
    areaLabel: "Área: ${value} ${unit}",
    distanceLabel: "Distancia: ${value} ${unit}",
    distanceLabelForLine: "Longitud: ${value} ${unit}",
    distanceLabelForPolygon: "Perímetro: ${value} ${unit}"
  }),
  "ar": 1,
  "bg": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sk": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
