define({
  root: ({
    showLegend: "Mostrar Leyenda",
    controlPopupMenuTitle: "Choose which actions will be shown on the layer context menu",
    zoomto: "Acercar a",
    transparency: "Transparencia",
    setVisibilityRange: "Set Visibility Range",
    controlPopup: "Habilitar / Deshabilitar pop-up",
    moveUpAndDown: "Mover arriba / Mover abajo",
    attributeTable: "Ver Tabla de Atributos",
    url: "Descripcion / Mostrar Detalles del Elemento / Descargar",
    showHideLabels: "Mostrar / Esconder Etiquetas",
    expandAllLayers: "Expander all layers",
    expandAllLayersByDefault: "Expander all layers by default",
    layerSelectorTitle: "Choose which layers will be shown on the list",
    showTitle: "Mostrar titulo",
    showBasemap: "Mostrar Mapabase"
  }),
  "ar": 1,
  "bg": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sk": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
