define({
  root: ({
    _widgetLabel: "Seleccionar",
    showActions: "Mostrar acciones en las entidades seleccionadas",
    toggleSelectability: "Haga clic para alternar la capacidad de selección",
    showSelectedFeatures: "Haga clic para mostrar las entidades seleccionadas",
    actionsTitle: "Acciones de selección",
    turnonAll: "Hacer que todas las capas sean seleccionables",
    turnoffAll: "Hacer que ninguna capa sea seleccionable",
    toggleSelect: "Alternar la capacidad de selección de todas las capas",
    singleSelect: "Convertir esta capa en la única seleccionable",
    enableByDefault: "Habilitar la herramienta Seleccionar de forma predeterminada"
  }),
  "ar": 1,
  "bg": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sk": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
