define({
  root: ({
    setSelectionColor: "Definir el color de selección",
    selectionMode: "Modo de selección interactivo",
    partiallyWithin: "Parcialmente dentro",
    whollyWithin: "Completamente dentro",
    allowExport: "Permitir la exportación de las entidades seleccionadas",
    layerToSelect: "Elegir qué capas están disponibles para seleccionar",
    includeRuntimeLayers: "Permitir la selección de capas generadas en tiempo de ejecución",
    enableByDefault: "Habilitar el botón Seleccionar de forma predeterminada"
  }),
  "ar": 1,
  "bg": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sk": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
