define({
  root: ({
    _widgetLabel: "Imprimir",
    title: "Título del mapa",
    format: "Formato",
    layout: "Diseño",
    settings: "Avanzado",
    labels: "Etiquetas",
    showLabels: "Mostrar etiquetas",
    mapScaleExtent: "Escala/extensión de mapa",
    preserve: "Preservar",
    mapScale: "escala de mapa",
    mapExtent: "extensión de mapa",
    forceScale: "Forzar escala",
    getCurrentScale: "actual",
    mapMetadata: "Metadatos de diseño",
    author: "Autor",
    copyright: "Copyright",
    fullLayoutOptions: "Opciones de diseño completo",
    scaleBarUnit: "Unidad de barra de escala",
    scaleBarUnitsMetric: "Unidades métricas de barra de escala",
    scaleBarUnitsNonMetric: "Unidades no métricas de barra de escala",
    unitsMiles: "Millas",
    unitsKilometers: "Kilómetros",
    unitsMeters: "Metros",
    unitsFeet: "Pies",
    unitsYards: "Yardas",
    unitsNauticalMiles: "Millas náuticas",
    lncludeLegend: "Incluir leyenda",
    printQualityOptions: "Calidad de impresión",
    dpi: "PPP",
    mapOnlyOptions: "Tamaño MAP_ONLY",
    width: "Ancho (px)",
    height: "Alto (px)",
    print: "Imprimir",
    clearList: "Borrar impresiones",
    creatingPrint: "Creando impresión",
    printError: "Error, vuelve a intentarlo",
    forceFeatureAttributes: "Atributos de entidad",
    includeFeatureAttributes: "Incluir atributos",
    outputSR: "Referencia espacial de salida",
    invalidWkid: "WKID no válido"
  }),
  "ar": 1,
  "bg": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sk": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
