define({
  root: ({
    _widgetLabel: "Lista de Capas",
    titleBasemap: "Basemaps",
    titleLayers: "Operational layers",
    labelLayer: "Nombre de Capa",
    itemZoomTo: "Acercar a",
    itemTransparency: "Transparencia",
    itemSetVisibilityRange: "Rango de Visualización",
    itemTransparent: "Transparente",
    itemOpaque: "Opaque",
    itemMoveUp: "Move up",
    itemMoveDown: "Move down",
    itemDesc: "Descripción",
    itemDownload: "Descargar",
    itemToAttributeTable: "Ver tabla de Atributos",
    itemShowItemDetails: "Motrar Detalles del Elemento",
    empty: "Vacio",
    removePopup: "Deshabilitar pop-up",
    enablePopup: "Habilitar pop-up",
    turnAllLayersOff: "Apagar Todas las Capas",
    turnAllLayersOn: "Prender Todas las Capas",
    expandAllLayers: "Expander Todas las Capas",
    collapseAlllayers: "Colapsar Todas las Capas",
    turnAllLabelsOff: "Apagar Todas las Etiquetas",
    turnAllLabelsOn: "Prender Todas las Etiquetas",
    showLabels: "Mostrar Etiquetas",
    hideLables: "Esconder Etiquetas",
    keyword: "Palabra Clave",
    basemapLayers: "Basemap layers",
    typeAKeywork: "Escribir Palabra Clave",
    layers: "Capas",
    tipLayerSearch: "Buscar Capas",
    tipLayerListOperation: "Layer list operations",
    tipLayerOperation: "Layer menus",
    tipClearText: "Limpiar Texto",
    collapseLayer: "Colapsar",
    expandLayer: "Expander"
  }),
  "ar": 1,
  "bg": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sk": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
